<?php

namespace dezmont765\yii2bundle\actions;

use dezmont765\yii2bundle\models\AParentActiveRecord;
use dezmont765\yii2bundle\models\ASubActiveRecord;
use Yii;
use yii\db\ActiveRecord;

/**
 * Created by PhpStorm.
 * User: Dezmont
 * Date: 30.04.2017
 * Time: 14:47
 * @property AParentActiveRecord $sub_model_parent_class
 * @property ASubActiveRecord $sub_model_class
 * @property ActiveRecord $model
 */
abstract class DynamicFieldsAction extends MainAction
{

    const SUB_MODELS = 'sub_models';
    const CATEGORY = 'category';
    public $fields = [];

    public $category = null;
    public $sub_model_class = null;

    public $sub_models = [];

    const SUB_MODEL_PARENT_CLASS = 'sub_model_parent_class';
    const BINDING_CLASS = 'binding_class';
    const SUB_MODEL_CLASS = 'sub_model_class';
    const CHILD_BINDING_ATTRIBUTE = 'child_binding_attribute';
    const PARENT_BINDING_ATTRIBUTE = 'parent_binding_attribute';

    public $binding_class = null;
    public $sub_model_parent_class = null;
    public $child_binding_attribute = null;
    public $parent_binding_attribute = null;
    public $model = null;


    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
        $this->category = Yii::$app->request->getBodyParam('category');
        if($this->category) {
            $this->sub_model_class = $this->getSubModelClass($this->sub_model_class, $this->category,
                                                             $this->sub_model_parent_class);
        }
    }


    public function getSubModelClass($sub_model_class, $category, $sub_model_parent_class) {
        /**
         * @var $sub_model_parent_class AParentActiveRecord
         */
        $sub_model_class =
            $sub_model_class ?? $sub_model_parent_class::getSubTableClassByCategory($category);
        return $sub_model_class;
    }


    public function getDefaultView() {
        return $this->controller->id . '-form';
    }


    public function run($id = null) {
        $this->model = $this->getModel($id);
    }


    abstract public function getModel($id);


    public function initModels() {
        if($this->sub_model_class !== null) {
            $this->loadModelsFromRequest($this->sub_models, $this->sub_model_class);
        }
    }


    public function loadModelsFromRequest(&$sub_models = [], $sub_model_class) {
        $sub_model_attribute_sets = Yii::$app->request->post($sub_model_class::_formName(), []);
        foreach($sub_model_attribute_sets as $key => $sub_model_attribute_set) {
            if(!isset($sub_models[$key]) || !$sub_models[$key] instanceof $sub_model_class) {
                $sub_models[$key] = new $sub_model_class;
            }
            $sub_models[$key]->attributes = $sub_model_attribute_set;
        }
        if(empty($sub_models)) {
            $sub_models[] = new $sub_model_class;
        }
    }


    public function save() {
        if($this->model->load(Yii::$app->request->post())) {
            if($this->model->save()) {
                foreach($this->sub_models as &$sub_model) {
                    $sub_model->{$this->child_binding_attribute} =
                        $this->model->{$this->parent_binding_attribute};
                    $sub_model->category = $this->category;
                    $sub_model->save();
                }
                return $this->controller->redirect(['update', 'id' => $this->model->id]);
            }
        }
    }


    public function getBindingClass($binding_class, $sub_model_parent_class) {
        return $binding_class ?? $sub_model_parent_class;
    }


    public function findModels() {
        if($this->sub_model_class !== null) {
            $sub_model_class = $this->sub_model_class;
            $sub_model_parent_class = $this->sub_model_parent_class;
            $category = $this->category;
            $boundary_attribute_value = $this->model->{$this->parent_binding_attribute};
            if($sub_model_class::tableName() !== $sub_model_parent_class::tableName()) {
                $binding_class = $this->getBindingClass($this->binding_class, $sub_model_parent_class);
                $this->sub_models = $sub_model_class::find()
                                                    ->joinWith($sub_model_class::getMainModelAttribute())
                                                    ->andWhere([$binding_class::tableName() . '.' .
                                                                $this->child_binding_attribute => $boundary_attribute_value])
                                                    ->andWhere(['category' => $category])
                                                    ->indexBy('id')
                                                    ->all();
            }
            else {
                $this->sub_models =
                    $sub_model_class::find()->where(['AND',
                                                     [$this->child_binding_attribute => $boundary_attribute_value],
                                                     ['category' => $category]])
                                    ->indexBy('id')
                                    ->all();
            }
        }
    }


    protected function transformSubModels() {
        return true;
    }
}