<?php
namespace dezmont765\yii2bundle\actions;

use dezmont765\yii2bundle\components\geometry\IllegalArgumentException;
use dezmont765\yii2bundle\models\AParentActiveRecord;
use dezmont765\yii2bundle\models\ASubActiveRecord;
use dezmont765\yii2bundle\models\MainActiveRecord;
use dezmont765\yii2bundle\widgets\PartialActiveForm;
use Yii;

/**
 * Created by PhpStorm.
 * User: Dezmont
 * Date: 08.05.2017
 * Time: 11:54
 * @property MainActiveRecord $model
 * @property AParentActiveRecord $sub_model_parent_class
 * @property ASubActiveRecord $sub_model_class
 * @property DynamicFieldsActionFieldsBundle[] | array $fields
 */
abstract class DynamicFieldsAction extends MainAction
{

    public $fields = [];


    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
        foreach($this->fields as $key => &$fields) {
            $fields = new DynamicFieldsActionFieldsBundle($fields);
        }
    }


    public function initModels() {
        foreach($this->fields as &$fields) {
            $fields->loadModelsFromRequest();
        }
    }


    public function save() {
        if($this->model->load(Yii::$app->request->post())) {
            if($this->model->save()) {
                foreach($this->fields as &$field) {
                    $field->saveChildModels($this->model);
                }
                return $this->controller->redirect(['update', 'id' => $this->model->id]);
            }
        }
    }


    public function findExistingSubModels() {
        if(!$this->model->isNewRecord) {
            foreach($this->fields as &$field) {
                $field->findChildModels($this->model);
            }
        }
    }


    const FIND_CHILD_SUB_MODELS = 'findChildSubModels';
    const FIND_CHILD_SUB_MODELS_VIA_PARENT_CLASS_RELATION = 'findChildSubModelsViaParentClassRelation';
    const FIND_CHILD_PARENT_MODELS_VIA_SUB_CLASS_RELATION = 'findChildParentModelsViaSubClassRelation';
    const FIND_CHILD_PARENT_MODELS = 'findChildParentModels';

    public $model = null;


    abstract public function getModel($id);


    public function run($id = null) {
        $this->model = $this->getModel($id);
        $this->model->load(Yii::$app->request->post());
    }


    public function getDefaultView() {
        return $this->controller->id . '-form';
    }


    public function getBindingClass($binding_class, $sub_model_parent_class) {
        return $binding_class ?? $sub_model_parent_class;
    }


}